### ISSUE TITLE
Usage to call .ready() and get Telegram.WebApp object

### ISSUE THREAD

**Issue by DmitryBobryakov** [davidsl4/react-telegram-webapp#1]
Hi,
 Can you provide a simple guide how to use your project? Im newbee in React and dont understand how to call .ready() in document.getElementById("root") and get Telegram.WebApp object in functional components.
If I try  
`const [telegramWebApp, setTelegramWebApp] = useTelegramWebApp();`
```
function sendPassword(): void {
        console.log('sendPassword');
        telegramWebApp.sendData("/main");
    }
```
I get error
`TypeError: can't access property "app", a.useContext(...) is null`
I suppose smth wrong in 
```
export type TelegramWebAppModel = {
    app: Telegram.Unsafe.WebApp;
    startParam: string | null;
    isReady: boolean;
};
```
 Can you help me please?

**Comment by davidsl4** [comment]
Hi @DmitryBobryakov, you get this exception because you haven't mounted the `TelegramWebApp` context in your application.

In your `App.tsx`, wrap your App component with the `withTelegramWebApp` hook exported from `react-telegram-webapp`, like this:

```ts
import React from 'react';
import { useTelegramWebApp, withTelegramWebApp } from "react-telegram-webapp";

function App() {
  const app = useTelegramWebApp();
  
  function sendPassword(): void {
    console.log('sendPassword');
    app.sendData('/main');
  }

  return <div>Hello World from React WebApp</div>;
}

export default withTelegramWebApp(App, {
  validateHash: () => true
});
```

I plan to upload a complete clone of the original Telegram web app demo using this library.

**Comment by DmitryBobryakov** [comment]
@davidsl4 Hi, again!
It works, thanks a lot.
Btw, for now here is new isssue- `.sendData("/start")` doesn't work anymore. I cannot find news about BotAPI updates after 16 April, but they changed smth about it.
.close() works as expected.
I tried .sendMessage("/start") like how it done on my bot server side, but it doesn't work too.
Do you have any ideas?

**Comment by davidsl4** [comment]
Hi, I can't find any changes related to the `sendData` function. Unfourtanetly, I can't test it right now, so I can't guarantee there are no issues with the library, but Telegram left there is a note that this function works only for web apps launched via a [Keyboard button](https://core.telegram.org/bots/webapps#keyboard-button-web-apps).

Please confirm you are launching the web app via a keyboard button.
